# Generated by Django 5.1.6 on 2026-09-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_file', models.FileField(blank=True, upload_to='datasets/')),
                ('mapping', models.JSONField(default=dict)),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('customers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_days', models.PositiveIntegerField(default=90)),
                ('feature_window_days', models.PositiveIntegerField(default=180)),
                ('best_model', models.CharField(blank=True, max_length=100)),
                ('metrics', models.JSONField(default=dict)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='predictor.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=120)),
                ('predicted_value', models.FloatField()),
                ('segment', models.CharField(max_length=20)),
                ('features', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.modelrun')),
            ],
            options={
                'indexes': [models.Index(fields=['customer_id'], name='predictor_c_custome_fdd7dd_idx'), models.Index(fields=['segment'], name='predictor_c_segment_cf31d5_idx')],
            },
        ),
    ]
